# Generated by Django 6.0.6 on 2026-06-26 10:18

import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('excel_clean', 'Excel tozalash/deduplikatsiya'), ('excel_to_pdf', 'Excel -> PDF hisobot'), ('pdf_table_extract', 'PDF jadval -> Excel')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Qayta ishlanmoqda'), ('done', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=16)),
                ('input_file', models.FileField(upload_to=files.models.upload_to_input)),
                ('result_file', models.FileField(blank=True, null=True, upload_to=files.models.upload_to_output)),
                ('error_message', models.TextField(blank=True, default='')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
