# Generated by Django 6.0.6 on 2026-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('excel_clean', 'Excel tozalash/deduplikatsiya'), ('excel_to_pdf', 'Excel -> PDF hisobot'), ('pdf_table_extract', 'PDF jadval -> Excel'), ('docx_to_pdf', 'Word -> PDF'), ('pdf_text_extract', 'PDF matn -> Word')], max_length=32),
        ),
    ]
